### ISSUE TITLE
Error with large repo

### ISSUE THREAD

**Issue by HaroldPutman** [jayproulx/vlt-watch#6]
The default maxBuffer size is [supposed to be 200*1024](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options)
and `wc` says my checkout only outputs 74814 bytes, but I get this error.  I fixed it to accommodate more output by bumping up the maxBuffer option in call to child_process.exec() but maybe we should use child_process.spawn to stream the output instead.

```
{ Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:259:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
  cmd: 'vlt --credentials admin:admin checkout --force http://localhost:4502/crx /Users/haputman/Projects/aem-lexmark/common/vault/jcr_root' }
```

**Comment by jayproulx** [comment]
You mentioned you fixed this by adding an option, feel free to send that as a pull request until we refactor for cp.spawn, this is a good suggestion.
